"""initial schema with pipeline_runs

Revision ID: b1f616ccca62
Revises: 
Create Date: 2026-02-06 21:58:31.768709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.models.base


# revision identifiers, used by Alembic.
revision: str = 'b1f616ccca62'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('details', src.models.base.JSONType(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('therapists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cognito_sub', sa.String(length=255), nullable=False),
    sa.Column('email_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('practice_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('therapists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_therapists_cognito_sub'), ['cognito_sub'], unique=True)

    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('therapist_id', sa.UUID(), nullable=False),
    sa.Column('name_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('contact_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('consent_status', sa.Enum('PENDING', 'ACTIVE', 'REVOKED', name='consentstatus'), nullable=False),
    sa.Column('consent_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("consent_status != 'active' OR consent_date IS NOT NULL", name='consent_date_required_when_active'),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapists.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Enum('RUNG', 'BETH', name='agentname'), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'name', name='unique_agent_per_client')
    )
    op.create_table('couple_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('partner_a_id', sa.UUID(), nullable=False),
    sa.Column('partner_b_id', sa.UUID(), nullable=False),
    sa.Column('therapist_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'TERMINATED', name='couplestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('partner_a_id != partner_b_id', name='different_partners'),
    sa.CheckConstraint('partner_a_id < partner_b_id', name='partner_a_less_than_b'),
    sa.ForeignKeyConstraint(['partner_a_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['partner_b_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapists.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partner_a_id', 'partner_b_id', name='unique_couple')
    )
    op.create_table('development_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('sprint_number', sa.Integer(), nullable=False),
    sa.Column('goals', src.models.base.JSONType(), nullable=False),
    sa.Column('exercises', src.models.base.JSONType(), nullable=False),
    sa.Column('progress', src.models.base.JSONType(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'sprint_number', name='unique_sprint_per_client')
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('session_type', sa.Enum('INDIVIDUAL', 'COUPLES', name='sessiontype'), nullable=False),
    sa.Column('session_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='sessionstatus'), nullable=False),
    sa.Column('notes_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('transcript_s3_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_guides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('content_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('key_points', src.models.base.JSONType(), nullable=False),
    sa.Column('exercises_suggested', src.models.base.JSONType(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clinical_briefs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('content_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('frameworks_identified', src.models.base.JSONType(), nullable=False),
    sa.Column('risk_flags', src.models.base.JSONType(), nullable=False),
    sa.Column('research_citations', src.models.base.JSONType(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('framework_merges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('couple_link_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('partner_a_frameworks', src.models.base.JSONType(), nullable=False),
    sa.Column('partner_b_frameworks', src.models.base.JSONType(), nullable=False),
    sa.Column('merged_insights', src.models.base.JSONType(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['couple_link_id'], ['couple_links.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pipeline_type', sa.String(length=50), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('couple_link_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_stage', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_json', src.models.base.JSONType(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipeline_runs_pipeline_type'), ['pipeline_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_runs_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_runs_status'))
        batch_op.drop_index(batch_op.f('ix_pipeline_runs_pipeline_type'))

    op.drop_table('pipeline_runs')
    op.drop_table('framework_merges')
    op.drop_table('clinical_briefs')
    op.drop_table('client_guides')
    op.drop_table('sessions')
    op.drop_table('development_plans')
    op.drop_table('couple_links')
    op.drop_table('agents')
    op.drop_table('clients')
    with op.batch_alter_table('therapists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_therapists_cognito_sub'))

    op.drop_table('therapists')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
